start: "Привет!"
error_access_1: "У вас нет доступа к этому боту.\n"
error_access_2: "Ваш ID: `"
error_access_3: "`\n"
error_access_4: "Обратись к администратору и передайте свой ID для получения доступа."
error_ffmpeg: "Голос временно не работает: отсутствует ffmpeg."
error_short_gs_message: "Слишком короткое голосовое сообщение (менее 0.5 сек)."
error_recognize: "Не удалось распознать речь (Vosk ничего не разобрал)."
error_voice: "Ошибка при обработке голосового сообщения: "
error_message: "Произошла ошибка при обработке."
error_parse_message: "Произошла ошибка при обработке сообщения от llm."
error_llm_1: "Извините, не удалось получить ответ от модели."
error_llm_2: "Превышено время ожидания ответа от модели."
error_llm_3: "Ошибка связи с моделью."
error_llm_4: "Внутренняя ошибка при обработке запроса."
